export const items = [
  {
    id: "341",
    img: "/Gallery/341s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 479,
  },
  {
    id: "vid1",
    type: "video",
    src: "/Gallery/video/v1.mp4",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 720,
  },
  
  {
    id: "467",
    img: "/Gallery/467s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 456,
  },
  
  {
    id: "367",
    img: "/Gallery/367s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 625,
  },
  {
    id: "33",
    img: "/Gallery/33.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 371,
  },
  {
    id: "466",
    img: "/Gallery/466s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 431,
  },
  {
    id: "47",
    img: "/Gallery/47.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 689,
  },
  {
    id: "145",
    img: "/Gallery/145s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 389,
  },
  {
    id: "34",
    img: "/Gallery/34.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 455,
  },
  {
    id: "155",
    img: "/Gallery/155s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 255,
  },
  {
    id: "42",
    img: "/Gallery/42.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 387,
  },
  {
    id: "106",
    img: "/Gallery/106s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 608,
  },
  {
    id: "11",
    img: "/Gallery/11.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 657,
  },
  {
    id: "343",
    img: "/Gallery/343s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 507,
  },
  {
    id: "270",
    img: "/Gallery/270s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 409,
  },
  {
    id: "49",
    img: "/Gallery/49.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 981,
  },
  {
    id: "153",
    img: "/Gallery/153s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 499,
  },
  {
    id: "17",
    img: "/Gallery/17.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 621,
  },
  {
    id: "250",
    img: "/Gallery/250s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 359,
  },
  {
    id: "143",
    img: "/Gallery/143s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 385,
  },
  {
    id: "206",
    img: "/Gallery/206s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 575,
  },
  {
    id: "314",
    img: "/Gallery/314s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 369,
  },
  {
    id: "32",
    img: "/Gallery/32.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 459,
  },
  {
    id: "1",
    img: "/Gallery/1.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 631,
  },
  {
    id: "336",
    img: "/Gallery/336s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 486,
  },
  {
    id: "18",
    img: "/Gallery/18.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 879,
  },
  {
    id: "235",
    img: "/Gallery/235s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 292,
  },
  {
    id: "15",
    img: "/Gallery/15.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 763,
  },
  {
    id: "256",
    img: "/Gallery/256s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 303,
  },
  {
    id: "468",
    img: "/Gallery/468s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 752,
  },
  {
    id: "40",
    img: "/Gallery/40.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 476,
  },
  {
    id: "37",
    img: "/Gallery/37.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 307,
  },
  {
    id: "100",
    img: "/Gallery/100s.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 332,
  },
  {
    id: "337",
    img: "/Gallery/337s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 542,
  },
  {
    id: "471",
    img: "/Gallery/471s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 501,
  },
  {
    id: "52",
    img: "/Gallery/52.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 259,
  },
  {
    id: "308",
    img: "/Gallery/308s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 579,
  },
  {
    id: "35",
    img: "/Gallery/35.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 536,
  },
  {
    id: "71",
    img: "/Gallery/71s.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 512,
  },
  {
    id: "144",
    img: "/Gallery/144s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 267,
  },
  {
    id: "307",
    img: "/Gallery/307s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 327,
  },
  {
    id: "339",
    img: "/Gallery/339s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 307,
  },
    {
    id: "vid",
    type: "video",
    src: "/Gallery/video/v2.mp4",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 720,
  },
  {
    id: "464",
    img: "/Gallery/464s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 543,
  },
  {
    id: "112",
    img: "/Gallery/112s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 538,
  },
  {
    id: "73",
    img: "/Gallery/73s.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 266,
  },
  {
    id: "50",
    img: "/Gallery/50.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 558,
  },
  {
    id: "233",
    img: "/Gallery/233s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 352,
  },
  {
    id: "195",
    img: "/Gallery/195s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 462,
  },
  {
    id: "39",
    img: "/Gallery/39.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 485,
  },
  {
    id: "236",
    img: "/Gallery/236s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 572,
  },
  {
    id: "363",
    img: "/Gallery/363s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 423,
  },
  {
    id: "306",
    img: "/Gallery/306s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 522,
  },
  {
    id: "79",
    img: "/Gallery/79s.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 453,
  },
  {
    id: "36",
    img: "/Gallery/36.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 488,
  },
  {
    id: "114",
    img: "/Gallery/114s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 755,
  },
  {
    id: "5",
    img: "/Gallery/5.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 563,
  },
  {
    id: "41",
    img: "/Gallery/41.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 428,
  },
  {
    id: "157",
    img: "/Gallery/157s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 552,
  },
  {
    id: "46",
    img: "/Gallery/46.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 562,
  },
  {
    id: "150",
    img: "/Gallery/150s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 558,
  },
  {
    id: "469",
    img: "/Gallery/469s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 565,
  },
  {
    id: "48",
    img: "/Gallery/48.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 912,
  },
  {
    id: "137",
    img: "/Gallery/137s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 443,
  },
  {
    id: "7",
    img: "/Gallery/7.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 521,
  },
  {
    id: "43",
    img: "/Gallery/43.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 503,
  },
  {
    id: "4",
    img: "/Gallery/4.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 689,
  },
  {
    id: "90",
    img: "/Gallery/90s.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 413,
  },
  {
    id: "272",
    img: "/Gallery/272s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 565,
  },
  {
    id: "228",
    img: "/Gallery/228s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 515,
  },
  {
    id: "205",
    img: "/Gallery/205s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 261,
  },
  {
    id: "139",
    img: "/Gallery/139s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 364,
  },
  {
    id: "311",
    img: "/Gallery/311s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 278,
  },
  {
    id: "9",
    img: "/Gallery/9.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 596,
  },
  {
    id: "126",
    img: "/Gallery/126s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 873,
  },
  {
    id: "105",
    img: "/Gallery/105s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 372,
  },
  {
    id: "161",
    img: "/Gallery/161s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 411,
  },
  {
    id: "154",
    img: "/Gallery/154s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 400,
  },
  {
    id: "340",
    img: "/Gallery/340s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 281,
  },
  {
    id: "51",
    img: "/Gallery/51.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 348,
  },
  {
    id: "185",
    img: "/Gallery/185s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 473,
  },
  {
    id: "10",
    img: "/Gallery/10.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 1203,
  },
  {
    id: "38",
    img: "/Gallery/38.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 796,
  },
  {
    id: "221",
    img: "/Gallery/221s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 630,
  },
  {
    id: "91",
    img: "/Gallery/91s.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 583,
  },
  {
    id: "104",
    img: "/Gallery/104s.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 614,
  },
  {
    id: "21",
    img: "/Gallery/21.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 373,
  },
  {
    id: "269",
    img: "/Gallery/269s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 506,
  },
  {
    id: "77",
    img: "/Gallery/77s.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 489,
  },
  {
    id: "312",
    img: "/Gallery/312s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 425,
  },
  {
    id: "142",
    img: "/Gallery/142s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 520,
  },
  {
    id: "119",
    img: "/Gallery/119s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 981,
  },
  {
    id: "334",
    img: "/Gallery/334s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 812,
  },
  {
    id: "44",
    img: "/Gallery/44.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 777,
  },
  {
    id: "465",
    img: "/Gallery/465s.jpg",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 750,
  },
  {
    id: "88",
    img: "/Gallery/88s.JPG",
    url: "https://www.instagram.com/swaas.gtbit/",
    height: 548,
  },
];
let hasPreloaded = false;

export const preloadGalleryImages = () => {
  // Yeh function sirf ek baar chalega
  if (hasPreloaded) return;
  hasPreloaded = true;

  console.log("Preloading gallery images on user intent...");

  // Safety check
  if (items && items.length > 0) {
    items.forEach((item) => {
      const img = new Image();
      img.src = item.img;
    });
  }
};
